[package]
name = "Zero-Knowledge"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.29", features = ["rand"] }
sha2 = "0.10.7"
rand = "0.8.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
